version: '3.8'

services:
  # Serviço da Evolution API
  evolution-api:
    image: atendai/evolution-api:v2.2.3
    restart: always
    environment:
      # Conecta ao banco de dados do Railway
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_PROVIDER: postgresql
      DATABASE_ENABLED: "true"
      
      # Chave de API para acessar a Evolution
      AUTHENTICATION_API_KEY: "agente24h-key"
      
      # Correção para o QR Code do WhatsApp
      CONFIG_SESSION_PHONE_VERSION: "2.3000.1023204200"

  # Serviço do N8N
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      # Esta variável faz o N8N usar o mesmo banco da Evolution API
      - DB_TYPE=postgres
      - DB_POSTGRESDB_HOST=${PGHOST}
      - DB_POSTGRESDB_PORT=${PGPORT}
      - DB_POSTGRESDB_DATABASE=${PGDATABASE}
      - DB_POSTGRESDB_USER=${PGUSER}
      - DB_POSTGRESDB_PASSWORD=${PGPASSWORD}
      - N8N_HOST=${RAILWAY_PUBLIC_DOMAIN}
      - WEBHOOK_URL=https://n8n-rag-agent.up.railway.app/

volumes:
  n8n_data:
