version: '3.8'

services:
  # Este serviço se chama 'postgres'. A API vai conseguir encontrá-lo por este nome.
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: your_strong_password_here
      POSTGRES_DB: evolution_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Nosso serviço da Evolution API
  api:
    image: atendai/evolution-api:v2.2.3
    restart: always
    ports:
      - "8080:8080" # Expõe a porta para acessarmos a API
    environment:
      # Esta URL agora aponta para o serviço 'postgres' acima. Vai funcionar.
      DATABASE_URL: "postgresql://evolution:your_strong_password_here@postgres:5432/evolution_db"
      
      # Chaves e configurações da API
      AUTHENTICATION_API_KEY: "agente24h-key"
      CONFIG_SESSION_PHONE_VERSION: "2.3000.1023204200"
    depends_on:
      - postgres # Garante que o banco de dados inicie antes da API

volumes:
  postgres_data:
