version: "3.1"

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PORT=5678
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always

  evolution-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:KcGuOueOxdEYgIobUVLxtXDaOpmtKgYi@switchback.proxy.rlwy.net:42262/railway"
      DATABASE_PROVIDER: postgresql
    restart: always

volumes:
  n8n_data:
